image:
  registry: "docker.io"
  repository: ~
  tag: ~
  pullPolicy: "IfNotPresent"

application:
  port: ~
  health:
    enabled: false
    path: "/api/_health"
    initialDelaySeconds: 30
    periodSeconds: 30
  replicas: 1
  annotations: {}

automountServiceAccountToken: false

securityContext:
  pod: {}
  container: {}

resources: {}

nodePort:
  enabled: false
  port: ~
  labels: {}

clusterip:
  enabled: false
  port: 8080
  protocol: TCP
  labels: {}

ingress:
  enabled: false
  ingressClassName: "nginx"
  host: ~
  tls: []
  labels: {}
  annotations: {}

labels: {}
env: []
volumeMounts: []
volumes: []
initContainers: []
