{{- $name := include "app.name" . -}}
{{- $labels := include "app.labels" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- $labels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- $labels | nindent 8 }}
    spec:
      {{- if .Values.securityContext.pod }}
      securityContext:
        {{- toYaml .Values.securityContext.pod | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      containers:
        - name: {{ $name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.securityContext.container }}
          securityContext:
          {{- toYaml .Values.securityContext.container | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.env }}
          env:
          {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          {{- if .Values.volumeMounts }}
          volumeMounts:
          {{- toYaml .Values.volumeMounts | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.application.port }}
          {{- if .Values.application.health.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.application.health.path }}
              port: {{ .Values.application.port }}
            initialDelaySeconds: {{ .Values.application.health.initialDelaySeconds }}
            periodSeconds: {{ .Values.application.health.periodSeconds }}
          {{- end }}
      {{- if .Values.volumes }}
      volumes:
      {{- toYaml .Values.volumes | nindent 8 }}
      {{- end }}
