{{- $name := include "app.name" . -}}
{{- $labels := include "app.labels" . -}}
{{- $selectorLabels := include "app.selectorLabels" . -}}

{{- if .Values.nodePort.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-nodeport
  labels:
    {{- if .Values.nodePort.labels }}
    {{- toYaml .Values.nodePort.labels | nindent 4 }}
    {{ else }}
    {{- $labels | nindent 4 }}
    {{- end }}
spec:
  type: NodePort
  ports:
   - port: {{ .Values.application.port }}
     nodePort: {{ .Values.nodePort.port }}
  selector:
    {{- $selectorLabels | nindent 4 }}
{{- end }}
