name: Helm-Template
on:
  push:
    branches: ["main"]
    paths: ["charts/argocd/**"]


jobs:
  helm-template:
    name: Helm-Template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Helm Template
        run: |
          set -eux
          for filename in ./test/*.yaml; do
              helm template --values "$filename" ./charts/generic
          done
